---
name: Link Check
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  schedule:
    - cron: '0 9 * * 6'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  linkspector-check-links:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: umbrelladocs/action-linkspector@v1
        with:
          config_file: .github/configs/.linkspector.yml
          fail_level: any
          filter_mode: nofilter
          github_token: ${{ secrets.github_token }}
          reporter: github-check
